// <auto-generated />
using System;
using Eaship.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Eaship.Migrations
{
    [DbContext(typeof(EashipDbContext))]
    [Migration("20251023184233_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresEnum(modelBuilder, "eaship", "user_role", new[] { "renter", "admin" });
            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "citext");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Eaship.Models.Booking", b =>
                {
                    b.Property<long>("BookingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("BookingId"));

                    b.Property<string>("CargoDesc")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cargo_desc");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("DestinationPort")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("destination_port");

                    b.Property<int>("DurationDays")
                        .HasColumnType("integer")
                        .HasColumnName("duration_days");

                    b.Property<decimal>("HargaTotal")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("harga_total");

                    b.Property<string>("OriginPort")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("origin_port");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("start_date");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<int>("UserId")
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    b.HasKey("BookingId");

                    b.ToTable("booking", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.BookingTongkang", b =>
                {
                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<long>("TongkangId")
                        .HasColumnType("bigint")
                        .HasColumnName("tongkang_id");

                    b.Property<long?>("BookingId1")
                        .HasColumnType("bigint");

                    b.Property<int?>("DaysAllocated")
                        .HasColumnType("integer");

                    b.Property<int?>("SequenceNo")
                        .HasColumnType("integer");

                    b.Property<long?>("TongkangId1")
                        .HasColumnType("bigint");

                    b.HasKey("BookingId", "TongkangId");

                    b.HasIndex("BookingId1");

                    b.HasIndex("TongkangId");

                    b.HasIndex("TongkangId1");

                    b.ToTable("booking_tongkang", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.Company", b =>
                {
                    b.Property<int>("CompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("CompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("contact");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("NPWP")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("npwp");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("name");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("CompanyId");

                    b.ToTable("company", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.Contract", b =>
                {
                    b.Property<long>("ContractId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("ContractId"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("approved_at");

                    b.Property<long>("BookingId")
                        .HasColumnType("bigint")
                        .HasColumnName("booking_id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("OwnerSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("owner_signed");

                    b.Property<DateTime?>("OwnerSignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("owner_signed_at");

                    b.Property<string>("OwnerSigner")
                        .HasColumnType("text")
                        .HasColumnName("owner_signer");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("pdf_url");

                    b.Property<bool>("RenterSigned")
                        .HasColumnType("boolean")
                        .HasColumnName("renter_signed");

                    b.Property<DateTime?>("RenterSignedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("renter_signed_at");

                    b.Property<string>("RenterSigner")
                        .HasColumnType("text")
                        .HasColumnName("renter_signer");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at");

                    b.HasKey("ContractId");

                    b.ToTable("contract", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.Invoice", b =>
                {
                    b.Property<int>("InvoiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("invoice_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("InvoiceId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("amount");

                    b.Property<long>("ContractId")
                        .HasColumnType("bigint")
                        .HasColumnName("contract_id");

                    b.Property<DateTime?>("DueDate")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("due_date");

                    b.Property<DateTime>("IssuedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("issued_at");

                    b.Property<string>("Number")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("number");

                    b.Property<DateTime?>("PaidAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("paid_at");

                    b.Property<string>("PdfUrl")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("pdf_url");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("InvoiceId");

                    b.ToTable("invoice", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.Tongkang", b =>
                {
                    b.Property<long>("TongkangId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tongkang_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TongkangId"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<int?>("CompanyId1")
                        .HasColumnType("integer");

                    b.Property<bool>("IncludeTugboat")
                        .HasColumnType("boolean")
                        .HasColumnName("include_tugboat");

                    b.Property<string>("KapasitasDwt")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kapasitas_dwt");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("name");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("TongkangId");

                    b.HasIndex("CompanyId1");

                    b.ToTable("tongkang", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.TongkangTugboat", b =>
                {
                    b.Property<long>("TongkangId")
                        .HasColumnType("bigint")
                        .HasColumnName("tongkang_id");

                    b.Property<long>("TugboatId")
                        .HasColumnType("bigint")
                        .HasColumnName("tugboat_id");

                    b.Property<long?>("TongkangId1")
                        .HasColumnType("bigint");

                    b.Property<long?>("TugboatId1")
                        .HasColumnType("bigint");

                    b.HasKey("TongkangId", "TugboatId");

                    b.HasIndex("TongkangId1");

                    b.HasIndex("TugboatId");

                    b.HasIndex("TugboatId1");

                    b.ToTable("tongkang_tugboat", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.Tugboat", b =>
                {
                    b.Property<long>("TugboatId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("tugboat_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<long>("TugboatId"));

                    b.Property<long>("CompanyId")
                        .HasColumnType("bigint")
                        .HasColumnName("company_id");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("nama");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<string>("TugboatHp")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("tugboat_hp");

                    b.HasKey("TugboatId");

                    b.ToTable("tugboat", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.User", b =>
                {
                    b.Property<int>("UserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("user_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("UserId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("citext")
                        .HasColumnName("email");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("full_name");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_login_at");

                    b.Property<byte[]>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_hash");

                    b.Property<byte[]>("PasswordSalt")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("password_salt");

                    b.Property<int?>("RenterCompanyId")
                        .HasColumnType("integer")
                        .HasColumnName("renter_company_id");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("role");

                    b.HasKey("UserId");

                    b.ToTable("users", "public");
                });

            modelBuilder.Entity("RenterCompany", b =>
                {
                    b.Property<int>("RenterCompanyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("renter_company_id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("RenterCompanyId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("address");

                    b.Property<string>("Contact")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("contact");

                    b.Property<string>("NPWP")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)")
                        .HasColumnName("npwp");

                    b.Property<string>("Nama")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("nama");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.HasKey("RenterCompanyId");

                    b.ToTable("renter_company", "eaship");
                });

            modelBuilder.Entity("Eaship.Models.BookingTongkang", b =>
                {
                    b.HasOne("Eaship.Models.Booking", null)
                        .WithMany("BookingTongkangs")
                        .HasForeignKey("BookingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eaship.Models.Booking", "Booking")
                        .WithMany()
                        .HasForeignKey("BookingId1");

                    b.HasOne("Eaship.Models.Tongkang", null)
                        .WithMany()
                        .HasForeignKey("TongkangId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Eaship.Models.Tongkang", "Tongkang")
                        .WithMany()
                        .HasForeignKey("TongkangId1");

                    b.Navigation("Booking");

                    b.Navigation("Tongkang");
                });

            modelBuilder.Entity("Eaship.Models.Tongkang", b =>
                {
                    b.HasOne("Eaship.Models.Company", null)
                        .WithMany("Tongkangs")
                        .HasForeignKey("CompanyId1");
                });

            modelBuilder.Entity("Eaship.Models.TongkangTugboat", b =>
                {
                    b.HasOne("Eaship.Models.Tongkang", null)
                        .WithMany()
                        .HasForeignKey("TongkangId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eaship.Models.Tongkang", "Tongkang")
                        .WithMany()
                        .HasForeignKey("TongkangId1");

                    b.HasOne("Eaship.Models.Tugboat", null)
                        .WithMany()
                        .HasForeignKey("TugboatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Eaship.Models.Tugboat", "Tugboat")
                        .WithMany()
                        .HasForeignKey("TugboatId1");

                    b.Navigation("Tongkang");

                    b.Navigation("Tugboat");
                });

            modelBuilder.Entity("Eaship.Models.Booking", b =>
                {
                    b.Navigation("BookingTongkangs");
                });

            modelBuilder.Entity("Eaship.Models.Company", b =>
                {
                    b.Navigation("Tongkangs");
                });
#pragma warning restore 612, 618
        }
    }
}
